# Generated by Django 5.2.7 on 2025-11-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
