# Generated by Django 5.2.7 on 2025-11-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petguard', '0002_animal_apelido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='descricao',
            new_name='observacoes',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Em tratamento', 'Em tratamento'), ('Adotado', 'Adotado')], max_length=20),
        ),
    ]
