# Generated by Django 5.2.7 on 2025-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petguard', '0003_rename_descricao_animal_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
        migrations.AddField(
            model_name='animal',
            name='anos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='meses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_tratamento', 'Em tratamento'), ('adotado', 'Adotado')], default='disponivel', max_length=20),
        ),
    ]
