# Generated by Django 5.2.7 on 2025-11-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petguard', '0004_remove_animal_idade_animal_anos_animal_meses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='apelido',
            field=models.CharField(default='sem apelido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='petguard.especie'),
        ),
    ]
