# Generated by Django 5.2.7 on 2025-11-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petguard', '0005_especie_alter_animal_apelido_alter_animal_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petguard.especie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(default='disponivel', max_length=50),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
